### ISSUE TITLE
Usage of undefined gobuffalo/genny.GoBin()

### ISSUE THREAD

**Issue by navionguy** [gobuffalo/gogen#2]
In gogen/gomods/init.go line 61
and in gogen/gomods/tidy.go line 17

a call is made to genny.GoBin()

There is no such function defined in gobuffalo/genny as it currently exists in the repository.

**Comment by stanislas-m** [comment]
Hello, this repository is deprecated, you should use github.com/gobuffalo/genny/gogen instead. :)
